module.exports = {
	current: '2.43',
	previous: '2.42',
	date: '2026-07-01',
	time: '12:00 CST',
	level: 'minor',
	levelText: 'setData路径优化 + 死代码清理',
	name: 'B31 setData 路径优化',
	summary: 'editor_cmpt.js bindTextareaInput 改为路径式 setData、calendar_lib.js animation/touchDirection 合并 setData、tools.wxs 移除死代码。',
	changeLog: '/docs/version-change-diary.md',
	history: [
	{
		version: '2.43',
		date: '2026-07-01',
		name: 'B31 setData 路径优化',
		summary: 'editor_cmpt.js bindTextareaInput 改为路径式 setData、calendar_lib.js animation/touchDirection 合并 setData、tools.wxs 移除死代码 msg。',
		items: [
			'editor_cmpt.js bindTextareaInput: 全量 setData({nodeList}) → 路径式 setData({[`nodeList[${idx}].val`]: val})，减少diff计算',
			'calendar_lib.js listTouchEnd: 触屏方向清除合并到 animation setData，减少1次无谓 setData',
			'calendar_lib.js bindToNowTap: animation: fade 合并到 month/year/fold setData，减少1次 setData',
			'tools.wxs: 移除死代码 module.exports.msg = "hello tools"',
		],
	},
	{
		version: '2.42',
		date: '2026-06-25',
		name: '全量编码修复 + v2.42',
		summary: '完整扫描569个前端文件，消除所有U+FFFD乱码字符，恢复全链路中文显示。',
		items: [
			'完整扫描569个JS/WXML/WXSS/JSON文件，消除全部U+FFFD替换字符',
			'rewrite version.js/setting.js/work_admin_ai相关文件为纯UTF-8',
		],
	},
	{
		version: '2.41',
		date: '2026-06-25',
		name: 'CC Switch + 乱码修复',
		summary: '修复 WXML/WXSS/JS/version.js 中文编码乱码问题，Agnes 和 MiMo 双供应商云端配置完成。',
		items: [
			'修复 WXML/WXSS/JS/version.js/version_history.js 中文编码乱码',
			'Agnes 和 MiMo 双供应商 API Key 全部配置完毕，全云端运行',
			'增量部署 mcloud 云函数 live patch（32.8 KB）',
			'上传开发版 v2.41（1.6 MB）',
		],
	},
	{
		version: '2.40',
		date: '2026-06-25',
		name: 'CC Switch 多供应商切换',
		summary: '供应商配置改为多供应商卡片管理，后端支持 providers[] 列表存储和运行时路由，前端参考 CC Switch 设计重构。预填 Agnes 和 MiMo 两个供应商。',
		items: [
			'后端存储从单配置改为 providers[] 列表 + activeProviderId，支持任意数量供应商独立保存',
			'新增 PROVIDERS_STORE_KEY 和 _getProvidersConfig / _getActiveProviderConfig / saveProvidersConfig',
			'旧单配置自动迁移到新多供应商格式',
			'chat() 运行时根据 activeProviderId 取对应配置发请求',
			'前端重写为 CC Switch 风格：活跃供应商卡片 + 供应商列表 + 内联编辑器 + 折叠高级设置',
			'预填 Agnes（agnes-20-flash）和 MiMo（mimo-v2.5）两个供应商，API Key 已内置',
			'启用开关、切换供应商、编辑保存、测试对话均自动调用后端保存',
		],
	},
	{
		version: '2.30',
		date: '2026-06-25',
		name: 'v2.30-b30: 默认AI供应商替换为Agnes',
		summary: 'B30: 默认AI供应商从Mimo替换为Agnes，预填Key和模型配置，开箱即用。',
		items: [
			'DEFAULT_CONFIG enabled: false -> true。',
			'providerName: Mimo -> Agnes, model: mimo-v2.5 -> agnes-20-flash。',
			'apiUrl 从 xiaomimimo.com/v1 改为 api.agnes-ai.com/v1。',
			'visionApiUrl/visionModel 从空值预填为 Agnes 视觉模型。',
			'apiKey 预填为有效 Key，开箱即用不再需要手动填写。',
			'移除一处硬编码 Mimo 回退引用，改为 DEFAULT_CONFIG.providerName 动态引用。',
			'live_patch 同步重新打包。',
		],
	},
	],
};
