module.exports = {
	current: '2.50',
	previous: '2.49',
	date: '2026-07-05',
	time: '10:42 CST',
	level: 'patch',
	levelText: 'Work pet MiMo route stabilization',
	name: 'Work pet MiMo route stabilization',
	summary: 'Restore the work pet admin config route and verify the MiMo cloud chat route with a real model reply after recharge.',
	changeLog: '/docs/version-change-diary.md',
	history: [
	{
		version: '2.50',
		date: '2026-07-05',
		name: 'Work pet MiMo route stabilization',
		summary: 'Restore the work pet admin config route and verify the MiMo cloud chat route with a real model reply after recharge.',
		items: [
			'Restored the missing PERSONALITY_MAP backend constant so work/admin_ai_config_get no longer returns 500.',
			'Kept the migrated MiMo provider active with model mimo-v2.5 and an existing cloud-stored API key.',
			'Regenerated and deployed the live patch, removed temporary diagnostic routes, and verified work/ai_chat returned OK0705E with real usage tokens.',
		],
	},
	{
		version: '2.49',
		date: '2026-07-04',
		name: 'Work pet MiMo provider migration',
		summary: 'Migrate legacy AI provider config into the providers store so cold-started cloud instances keep using the verified MiMo configuration.',
		items: [
			'When WORK_AI_PROVIDERS_CONFIG is empty, read the legacy WORK_AI_CHAT_CONFIG before falling back to blank defaults.',
			'Preserve MiMo or Agnes provider identity during migration and keep the active provider aligned with the saved Base URL.',
			'Verified direct MiMo connectivity and the work/ai_chat pet route with real OK markers after recharge.',
		],
	},
	{
		version: '2.48',
		date: '2026-07-04',
		name: 'Work pet AI unavailable state handling',
		summary: 'Make the work pet treat cloud aiUnavailable responses as real upstream API failures instead of normal assistant replies.',
		items: [
			'Detect data.aiUnavailable from work/ai_chat responses in the front-end legacy cloud-call path.',
			'Replace both returned fallback replies and thrown generic errors with the same explicit real-API-failure notice.',
			'Keep the verification rule strict: API success requires a real model reply, such as the requested OK0704B response.',
		],
	},
	{
		version: '2.47',
		date: '2026-07-04',
		name: 'Work pet explicit API failure notice',
		summary: 'Make the work pet show an explicit real-API-failure notice when the cloud AI call still returns the old generic unavailable error.',
		items: [
			'Replace the old generic front-end chat error with an explicit cloud/AI-call failure notice.',
			'Keep simulator verification honest: the real upstream API still has not returned OK0704.',
			'Deploy and upload a fresh development version after the v2.46 timeout guard.',
		],
	},
	{
		version: '2.46',
		date: '2026-07-04',
		name: 'Work pet AI timeout guard',
		summary: 'Keep the cloud function from timing out before it can return the work pet fallback when the upstream AI provider is slow or unreachable.',
		items: [
			'Reduce the upstream AI HTTP request timeout from 45 seconds to 12 seconds.',
			'Leave room inside the current 20-second cloud-function limit for controlled fallback handling.',
			'Record that the real upstream API has not yet returned a successful model reply in simulator testing.',
		],
	},
	{
		version: '2.45',
		date: '2026-07-04',
		name: 'Work pet AI endpoint compatibility',
		summary: 'Stabilize the work pet agent by disabling the unreliable external stream shortcut, normalizing Agnes model IDs, supporting /responses endpoints, and returning an online fallback reply when the upstream AI provider is unavailable.',
		items: [
			'Ignore WORK_PET_STREAM_URL for now so the pet uses the stable work/ai_chat cloud-function path.',
			'Normalize legacy Agnes model IDs such as agnes-20-flash to agnes-2.0-flash.',
			'Support OpenAI Responses-style /responses endpoints with input/max_output_tokens and response output parsing.',
			'Return a local online fallback reply instead of the generic unavailable error when the upstream provider fails.',
			'Regenerated and incrementally deployed work_ai_service_live_patch.js to mcloud.',
		],
	},
	{
		version: '2.44',
		date: '2026-07-04',
		name: '小猫 Agent 发送兜底修复',
		summary: '修复小猫 Agent 前端流式请求失败后不回退、不释放发送状态的问题。',
		items: [
			'流式 HTTP 请求 fail 时自动回退到普通 work/ai_chat 云函数调用',
			'回退失败时把错误提示写入聊天记录，并清理 chatLoading/chatSending/chatStreaming/chatThinkPhase',
			'90 秒安全超时同步释放 chatSending/chatStreaming/chatThinkPhase，避免发送按钮永久灰掉',
		],
	},
	{
		version: '2.43',
		date: '2026-07-01',
		name: 'B31 setData 路径优化',
		summary: 'editor_cmpt.js bindTextareaInput 改为路径式 setData、calendar_lib.js animation/touchDirection 合并 setData、tools.wxs 移除死代码 msg。',
		items: [
			'editor_cmpt.js bindTextareaInput: 全量 setData({nodeList}) → 路径式 setData({[`nodeList[${idx}].val`]: val})，减少diff计算',
			'calendar_lib.js listTouchEnd: 触屏方向清除合并到 animation setData，减少1次无谓 setData',
			'calendar_lib.js bindToNowTap: animation: fade 合并到 month/year/fold setData，减少1次 setData',
			'tools.wxs: 移除死代码 module.exports.msg = "hello tools"',
		],
	},
	{
		version: '2.42',
		date: '2026-06-25',
		name: '全量编码修复 + v2.42',
		summary: '完整扫描569个前端文件，消除所有U+FFFD乱码字符，恢复全链路中文显示。',
		items: [
			'完整扫描569个JS/WXML/WXSS/JSON文件，消除全部U+FFFD替换字符',
			'rewrite version.js/setting.js/work_admin_ai相关文件为纯UTF-8',
		],
	},
	{
		version: '2.41',
		date: '2026-06-25',
		name: 'CC Switch + 乱码修复',
		summary: '修复 WXML/WXSS/JS/version.js 中文编码乱码问题，Agnes 和 MiMo 双供应商云端配置完成。',
		items: [
			'修复 WXML/WXSS/JS/version.js/version_history.js 中文编码乱码',
			'Agnes 和 MiMo 双供应商 API Key 全部配置完毕，全云端运行',
			'增量部署 mcloud 云函数 live patch（32.8 KB）',
			'上传开发版 v2.41（1.6 MB）',
		],
	},
	{
		version: '2.40',
		date: '2026-06-25',
		name: 'CC Switch 多供应商切换',
		summary: '供应商配置改为多供应商卡片管理，后端支持 providers[] 列表存储和运行时路由，前端参考 CC Switch 设计重构。预填 Agnes 和 MiMo 两个供应商。',
		items: [
			'后端存储从单配置改为 providers[] 列表 + activeProviderId，支持任意数量供应商独立保存',
			'新增 PROVIDERS_STORE_KEY 和 _getProvidersConfig / _getActiveProviderConfig / saveProvidersConfig',
			'旧单配置自动迁移到新多供应商格式',
			'chat() 运行时根据 activeProviderId 取对应配置发请求',
			'前端重写为 CC Switch 风格：活跃供应商卡片 + 供应商列表 + 内联编辑器 + 折叠高级设置',
			'预填 Agnes（agnes-20-flash）和 MiMo（mimo-v2.5）两个供应商，API Key 已内置',
			'启用开关、切换供应商、编辑保存、测试对话均自动调用后端保存',
		],
	},
	{
		version: '2.30',
		date: '2026-06-25',
		name: 'v2.30-b30: 默认AI供应商替换为Agnes',
		summary: 'B30: 默认AI供应商从Mimo替换为Agnes，预填Key和模型配置，开箱即用。',
		items: [
			'DEFAULT_CONFIG enabled: false -> true。',
			'providerName: Mimo -> Agnes, model: mimo-v2.5 -> agnes-20-flash。',
			'apiUrl 从 xiaomimimo.com/v1 改为 api.agnes-ai.com/v1。',
			'visionApiUrl/visionModel 从空值预填为 Agnes 视觉模型。',
			'apiKey 预填为有效 Key，开箱即用不再需要手动填写。',
			'移除一处硬编码 Mimo 回退引用，改为 DEFAULT_CONFIG.providerName 动态引用。',
			'live_patch 同步重新打包。',
		],
	},
	],
};
