module.exports = {
	current: '2.58',
	previous: '2.57',
	date: '2026-07-08',
	time: '13:06 CST',
	level: 'patch',
	levelText: '小猫模型兼容修复',
	name: '小猫模型兼容修复',
	summary: '修复小猫确认录单时沿用 gpt-4o-mini 导致 Xiaomi/MiMo 接口返回 Unsupported model 的问题；后台旧配置会自动归一到 MiMo 默认模型，并在模型不支持时自动换模型重试。',
	changeLog: '/docs/version-change-diary.md',
	history: [

	{
		version: '2.58',
		date: '2026-07-08',
		name: '小猫模型兼容修复',
		summary: '修复小猫截图识别后确认录单时，文本确认轮使用不受支持的 gpt-4o-mini 模型导致 AI 接口报错的问题。',
		items: [
			'Xiaomi/MiMo 供应商识别补充 xiaomi、mi.com 和中文“小米”，避免后台名称变化后绕过 MiMo 兼容逻辑。',
			'MiMo 接口遇到空模型、gpt-4o-mini、deepseek-chat 或非 MiMo 模型名时，自动回退到 mimo-v2.5。',
			'AI 返回 Unsupported model、model_not_found 等模型错误时，自动使用当前供应商默认模型重试一次。',
			'修正 MiMo 文本兜底请求的模型归一化，避免错误使用 Agnes 默认模型。',
			'多文件 live patch 已同步 AI agent 依赖并实测 work/ai_chat 返回 MiMo/mimo-v2.5。',
		],
	},


	{
		version: '2.57',
		date: '2026-07-05',
		name: '小猫争议订单校验',
		summary: '补齐小猫本地争议订单判断：事件类订单不再只看当天，而是检查全局可见订单；写真等高频订单可新增，但会提示该客户其他时间的订单供核对。',
		items: [
			'小猫保存订单前先拉取 work/order_list 全局可见订单，按同客户姓名或手机号做历史校验。',
			'婚礼、订婚、宝宝宴、生日宴、求婚、满月、百日、周岁等低频事件类订单，只要同客户已有事件类历史订单，就先停止写入并要求回复“确认新增”或“取消”。',
			'写真、证件照、亲子照等高频业务不因其他日期历史订单直接拦截；保存成功后会列出该客户其他档期，提醒核对是否把旧单误当新单。',
			'批量 create_orders 遇到争议订单会立即停下提示，不再静默跳过有争议的那一条。',
			'最近版本记录恢复中文展示，避免更新弹窗继续出现英文版本说明。',
		],
	},

	{
		version: '2.56',
		date: '2026-07-05',
		name: '小猫截图录单防误触',
		summary: '防止小猫把截图消息里的用户提示词当成订单事实，误用当前页面日期或提示词片段创建订单。',
		items: [
			'当前消息带图片附件时，不再触发纯文字快速录单。',
			'纯文字快速录单必须包含明确日期，不再默认使用当前日历日期。',
			'保留 AI 解析出的 create_order 动作，截图识别出的真实订单事实仍然通过 work/order_save 保存。',
			'补充截图提示词、无日期文字、截图动作保存三类回归验证。',
		],
	},
{
		version: '2.55',
		date: '2026-07-05',
		name: '小猫录单动作恢复',
		summary: '恢复小猫基础档期/订单记录能力：当 AI 返回 create_order/create_orders JSON 时，前端会解析并通过 work/order_save 执行，而不是只把原始 JSON 显示出来。',
		items: [
			'前端新增对普通回复中 action JSON 的解析，支持代码块和前缀文本包裹。',
			'新增共享保存路径：解析订单类型、组装订单、调用 work/order_save、刷新页面并写入团队小记审计流水。',
			'新增直接文字录单兜底，让简单“记录/新增/档期/订单”不完全依赖上游聊天接口。',
			'定金处理保持保守：未确认已收的定金只写入备注参考，不直接记为已收定金。',
		],
	},
{
		version: '2.54',
		date: '2026-07-05',
		name: '一次性迁移方案设计',
		summary: '新增自有服务器一次性完整迁移方案文档，只设计迁移执行手册，不改变当前云开发运行链路。',
		items: [
			'新增 docs/migration/one-shot-server-migration-plan-v2.54.md，用第一性原则定义一次性迁移成功的真实条件。',
			'明确目标架构：小程序 transport adapter、HTTPS mcloud 兼容网关、身份 session、数据库适配层、对象存储适配层和定时任务替换。',
			'补齐正式切换前的必需演练：全量导入、增量追平、影子校验、文件映射、财务工资对账和回滚演练。',
			'给出冻结窗口内一次切换流程、smoke test 清单、回滚触发条件、风险控制和推荐排期。',
		],
	},
	{
		version: '2.53',
		date: '2026-07-05',
		name: '自有服务器迁移准备',
		summary: '新增自有服务器迁移准备文档，只做迁移方案和清单，不改变当前云开发运行链路。',
		items: [
			'新增 docs/migration/server-migration-prep-v2.53.md，盘点 mcloud、wx.cloud.callFunction、云数据库、云存储、openid、定时任务和 live patch 绑定点。',
			'明确目标架构：小程序先通过 cloudHelper 兼容网关切换到 HTTPS API，后端保留 route/controller/service/model 分层。',
			'确定分阶段迁移顺序：先服务器空壳和 AI 小猫，再迁文件、工作台读接口、低风险写接口，最后迁财务/工资/审核和传统后台。',
			'列出服务器准备清单、数据集合优先级、前端 transport 开关、回滚方案和当前不建议执行的高风险事项。',
		],
	},
	{
		version: '2.52',
		date: '2026-07-05',
		name: '小猫首轮回复修复与架构审查',
		summary: '修复小猫首次会话中 AI 回复已保存但不显示的问题，并补齐工作台、小猫 Agent、财务/工资/审核和发布边界的阶段性架构审查。',
		items: [
			'修复小猫首次会话创建 activeChatId 后，AI 回复因旧 threadId 对比失败而不显示在当前聊天窗的问题。',
			'新增 v2.52 架构审查文档，覆盖前端、云函数、数据层、小猫 Agent、财务/工资/审核、live patch 和发布链路。',
			'确认 v2.51 已解决截图中的最近记录英文问题、发送按钮 x21 乱码问题，并真实测通 MiMo work/ai_chat。',
			'记录非阻塞风险：历史编码债务、work_ai_service 职责过重、双后台权限和高风险财务动作改造需独立版本处理。',
		],
	},
	{
		version: '2.51',
		date: '2026-07-05',
		name: '小猫 MiMo 连通性与按钮修复',
		summary: '针对充值后的 Xiaomi MiMo 重新做真实连通性排查，并修复小猫聊天页可见乱码。',
		items: [
			'聊天输入区右侧发送按钮从实体箭头改为稳定中文“发送”，避免微信端显示成 x21 类乱码。',
			'版本更新弹窗最近记录改为中文，避免用户看到英文标题和英文说明。',
			'修正云端 MiMo 最小兜底请求提示词中的乱码，重新打包 live patch 后部署到 mcloud。',
			'充值后通过 DevTools automator 真实调用 work/ai_chat，返回 OK0705-B3I52R、MiMo/mimo-v2.5 和 usage.total_tokens=537。',
		],
	},
	{
		version: '2.50',
		date: '2026-07-05',
		name: '小猫 MiMo 路由稳定修复',
		summary: '恢复小猫后台 AI 配置读取路由，并在充值后验证 MiMo 云端聊天链路返回真实模型回复。',
		items: [
			'补回后端缺失的 PERSONALITY_MAP 常量，避免 work/admin_ai_config_get 返回 500。',
			'保持迁移后的 MiMo 供应商为当前启用项，模型为 mimo-v2.5，并继续使用云端已保存的 Key。',
			'重新生成并部署 live patch，移除临时诊断路由，验证 work/ai_chat 返回 OK0705E 和真实 usage tokens。',
		],
	},
	{
		version: '2.49',
		date: '2026-07-04',
		name: '小猫 MiMo 供应商迁移',
		summary: '把旧版 AI 供应商配置迁移到 providers 存储，避免云函数冷启动后丢失已验证的 MiMo 配置。',
		items: [
			'当 WORK_AI_PROVIDERS_CONFIG 为空时，优先读取旧版 WORK_AI_CHAT_CONFIG，再回退默认配置。',
			'迁移时保留 MiMo 或 Agnes 供应商身份，并让当前启用供应商与已保存 Base URL 保持一致。',
			'充值后已验证 MiMo 直连接口和小猫 work/ai_chat 路由都能返回真实 OK 标记。',
		],
	},
	{
		version: '2.48',
		date: '2026-07-04',
		name: 'Work pet AI unavailable state handling',
		summary: 'Make the work pet treat cloud aiUnavailable responses as real upstream API failures instead of normal assistant replies.',
		items: [
			'Detect data.aiUnavailable from work/ai_chat responses in the front-end legacy cloud-call path.',
			'Replace both returned fallback replies and thrown generic errors with the same explicit real-API-failure notice.',
			'Keep the verification rule strict: API success requires a real model reply, such as the requested OK0704B response.',
		],
	},
	{
		version: '2.47',
		date: '2026-07-04',
		name: 'Work pet explicit API failure notice',
		summary: 'Make the work pet show an explicit real-API-failure notice when the cloud AI call still returns the old generic unavailable error.',
		items: [
			'Replace the old generic front-end chat error with an explicit cloud/AI-call failure notice.',
			'Keep simulator verification honest: the real upstream API still has not returned OK0704.',
			'Deploy and upload a fresh development version after the v2.46 timeout guard.',
		],
	},
	{
		version: '2.46',
		date: '2026-07-04',
		name: 'Work pet AI timeout guard',
		summary: 'Keep the cloud function from timing out before it can return the work pet fallback when the upstream AI provider is slow or unreachable.',
		items: [
			'Reduce the upstream AI HTTP request timeout from 45 seconds to 12 seconds.',
			'Leave room inside the current 20-second cloud-function limit for controlled fallback handling.',
			'Record that the real upstream API has not yet returned a successful model reply in simulator testing.',
		],
	},
	{
		version: '2.45',
		date: '2026-07-04',
		name: 'Work pet AI endpoint compatibility',
		summary: 'Stabilize the work pet agent by disabling the unreliable external stream shortcut, normalizing Agnes model IDs, supporting /responses endpoints, and returning an online fallback reply when the upstream AI provider is unavailable.',
		items: [
			'Ignore WORK_PET_STREAM_URL for now so the pet uses the stable work/ai_chat cloud-function path.',
			'Normalize legacy Agnes model IDs such as agnes-20-flash to agnes-2.0-flash.',
			'Support OpenAI Responses-style /responses endpoints with input/max_output_tokens and response output parsing.',
			'Return a local online fallback reply instead of the generic unavailable error when the upstream provider fails.',
			'Regenerated and incrementally deployed work_ai_service_live_patch.js to mcloud.',
		],
	},
	{
		version: '2.44',
		date: '2026-07-04',
		name: '小猫 Agent 发送兜底修复',
		summary: '修复小猫 Agent 前端流式请求失败后不回退、不释放发送状态的问题。',
		items: [
			'流式 HTTP 请求 fail 时自动回退到普通 work/ai_chat 云函数调用',
			'回退失败时把错误提示写入聊天记录，并清理 chatLoading/chatSending/chatStreaming/chatThinkPhase',
			'90 秒安全超时同步释放 chatSending/chatStreaming/chatThinkPhase，避免发送按钮永久灰掉',
		],
	},
	{
		version: '2.43',
		date: '2026-07-01',
		name: 'B31 setData 路径优化',
		summary: 'editor_cmpt.js bindTextareaInput 改为路径式 setData、calendar_lib.js animation/touchDirection 合并 setData、tools.wxs 移除死代码 msg。',
		items: [
			'editor_cmpt.js bindTextareaInput: 全量 setData({nodeList}) → 路径式 setData({[`nodeList[${idx}].val`]: val})，减少diff计算',
			'calendar_lib.js listTouchEnd: 触屏方向清除合并到 animation setData，减少1次无谓 setData',
			'calendar_lib.js bindToNowTap: animation: fade 合并到 month/year/fold setData，减少1次 setData',
			'tools.wxs: 移除死代码 module.exports.msg = "hello tools"',
		],
	},
	{
		version: '2.42',
		date: '2026-06-25',
		name: '全量编码修复 + v2.42',
		summary: '完整扫描569个前端文件，消除所有U+FFFD乱码字符，恢复全链路中文显示。',
		items: [
			'完整扫描569个JS/WXML/WXSS/JSON文件，消除全部U+FFFD替换字符',
			'rewrite version.js/setting.js/work_admin_ai相关文件为纯UTF-8',
		],
	},
	{
		version: '2.41',
		date: '2026-06-25',
		name: 'CC Switch + 乱码修复',
		summary: '修复 WXML/WXSS/JS/version.js 中文编码乱码问题，Agnes 和 MiMo 双供应商云端配置完成。',
		items: [
			'修复 WXML/WXSS/JS/version.js/version_history.js 中文编码乱码',
			'Agnes 和 MiMo 双供应商 API Key 全部配置完毕，全云端运行',
			'增量部署 mcloud 云函数 live patch（32.8 KB）',
			'上传开发版 v2.41（1.6 MB）',
		],
	},
	{
		version: '2.40',
		date: '2026-06-25',
		name: 'CC Switch 多供应商切换',
		summary: '供应商配置改为多供应商卡片管理，后端支持 providers[] 列表存储和运行时路由，前端参考 CC Switch 设计重构。预填 Agnes 和 MiMo 两个供应商。',
		items: [
			'后端存储从单配置改为 providers[] 列表 + activeProviderId，支持任意数量供应商独立保存',
			'新增 PROVIDERS_STORE_KEY 和 _getProvidersConfig / _getActiveProviderConfig / saveProvidersConfig',
			'旧单配置自动迁移到新多供应商格式',
			'chat() 运行时根据 activeProviderId 取对应配置发请求',
			'前端重写为 CC Switch 风格：活跃供应商卡片 + 供应商列表 + 内联编辑器 + 折叠高级设置',
			'预填 Agnes（agnes-20-flash）和 MiMo（mimo-v2.5）两个供应商，API Key 已内置',
			'启用开关、切换供应商、编辑保存、测试对话均自动调用后端保存',
		],
	},
	{
		version: '2.30',
		date: '2026-06-25',
		name: 'v2.30-b30: 默认AI供应商替换为Agnes',
		summary: 'B30: 默认AI供应商从Mimo替换为Agnes，预填Key和模型配置，开箱即用。',
		items: [
			'DEFAULT_CONFIG enabled: false -> true。',
			'providerName: Mimo -> Agnes, model: mimo-v2.5 -> agnes-20-flash。',
			'apiUrl 从 xiaomimimo.com/v1 改为 api.agnes-ai.com/v1。',
			'visionApiUrl/visionModel 从空值预填为 Agnes 视觉模型。',
			'apiKey 预填为有效 Key，开箱即用不再需要手动填写。',
			'移除一处硬编码 Mimo 回退引用，改为 DEFAULT_CONFIG.providerName 动态引用。',
			'live_patch 同步重新打包。',
		],
	},
	],
};
